### ISSUE TITLE
[Feature request]: migrate from NativeActivity to GameActivity

### ISSUE THREAD

**Issue by android-1995** [Rakashazi/emu-ex-plus-alpha#1089]
### Describe the feature

https://android-dot-google-developers.gonglchuangl.net/games/agdk/game-activity/migrate-native-activity

**Comment by Rakashazi** [comment]
Thanks for the suggestion. I can't use GameActivity directly since the apps still maintain compatibility with API level 9 but have already implemented many of the features in AGDK like improved frame pacing and window insets handling. The main advantage of GameActivity is better integration with the native Android UI components so I'll consider using it in the future when it becomes too difficult to keep compatibility with older API levels.

**Comment by android-1995** [comment]
you are welcome. Your project is very good

**Comment by android-1995** [comment]
you are welcome. Your project is very good
