### ISSUE TITLE
[Issue]: C++ Error when Compiling on Github Runner

### ISSUE THREAD

**Issue by hilltop804** [Rakashazi/emu-ex-plus-alpha#1274]
### Describe the bug

Hi, I was trying to compile using one of the Github hosted runners but I'm encountering an error related to std::span. This is a bit outside of my scope of knowledge, but I think this is related to a gcc/C++ version issue. I tried different versions of gcc, but it didn't help.

I also tried changing 'std=gnu++2b' to 'std=c++20' in the imagine/makegcc-common.mk file, but that caused a different 'std::' issue. I would appreciate any insight or advice you may be able to share.

If it's helpful - I spun up a Ubuntu VM, cloned the repo, and attempted to execute the same make functions. It didn't have this error there. I think whatever is happening is specific to the 'hosted runner' environment.

### Steps to reproduce

Run this code in a workflow file:

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y bash clang clang-15 cmake g++ g++-12 gcc gcc-12 gcc-12-base glibc-source lib32gcc-s1 lib32stdc++6
        sudo apt install -y libarchive-dev libasound2-dev libbluetooth-dev libdbus-1-3 libdrm-dev libegl-dev libfontconfig-dev
        sudo apt install -y libfreetype-dev libgl-dev liblzma-dev libpng-dev libpulse-dev libstdc++-12-dev libstdc++6
        sudo apt install -y libxfixes-dev libxi-dev libxrandr-dev zlib1g-dev
        
    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV
          
    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/linux-x86_64-release.mk install V=1 -j2
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk config -j2
        make -f $EMUFRAMEWORK_PATH/linux-x86_64-release.mk install V=1 -j2

### Expected behavior

The code should execute without error.

### Add screenshots

Error log:
![image](https://user-images.githubusercontent.com/41207087/226795925-9c5d9d1b-06c7-4881-a3bb-3ff17caf944e.png)

imagine/makegcc-common.mk:
![image](https://user-images.githubusercontent.com/41207087/226796317-b9f54189-4c63-47ed-b78a-684e5aaee7cf.png)

**Comment by Rakashazi** [comment]
Thanks for the report. I had a couple missing includes that went unnoticed due to the version of libc++ I used including them implicitly. Try out the last commit which should fix that and let me know if it builds correctly.

Also, std=gnu++2b corresponds to C++23 which is why the build had other failures when setting it to C++20 mode.

**Comment by Rakashazi** [comment]
That error is from a missing C++23 function in std::string so looks like you're actually compiling with an older version of gcc even though you installed 12. I think it's because on Ubuntu 22.04 the system gcc is 11 so you need to explicitly call g++-12 instead of just g++. Upgrading to Ubuntu 22.10 will also fix the issue since the gcc 12 is the default there. To get it working on Ubuntu 22.04, add CC=gcc-12 CXX=g++-12 to the end of any make commands.

The builds are currently tested with libstdc++ from GCC 12 and libc++ from LLVM 15, but I'm planning to move up to GCC 13 and LLVM 16 once they are stable so when that happens you'll need to update your workflow to install gcc-13 and g++-13, and pass them to make as shown above.

**Comment by hilltop804** [comment]
Thank you for the explanation! That's very helpful. I didn't realize it didn't automatically use the highest installed version. Adding those options fixed that error, but now there's a new one (screenshot below). I searched for that function and found a file that seems to be related to libarchive. Is this another version issue? I'm including libarchive-dev and libarchive13 in my package list.

(Please let me know if this is no longer related and I should open a new issue)

![image](https://user-images.githubusercontent.com/41207087/227390768-eeca2d18-7bfb-489f-b4db-edef26709bae.png)

![image](https://user-images.githubusercontent.com/41207087/227391014-c1cfbebf-343c-4f8b-88ea-45c878f1caab.png)

**Comment by Rakashazi** [comment]
I've patched libarchive with a few extra functions so that's the only dependency on Linux that must be built from the bundled libraries. Add this as the first run command of your build environment to build and install the custom version.

`(cd $IMAGINE_PATH/bundle/all/src/libarchive && make -f linux-x86_64.mk install V=1 -j2)`

**Comment by hilltop804** [comment]
Thanks for the response! I was able to get the environment and emulator build to compile, so I'm going to close this item.

For anyone who finds this later - I've included the yml code below to successfully compile GBA on Ubuntu-22.04

**Comment by Rakashazi** [comment]
Thanks and good to hear you got it working. Currently the Linux versions are mainly for testing but I'm planning to add official builds for them in the future.
