### ISSUE TITLE
[Issue]: Can't save ram when "Auto Save Lanuch Mode" is "No Save slot"

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1363]
### Describe the bug

When the option is selected, the ram file can't be created.
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1002
In fact, "Autosave Content" is "Only Backup Ram" can disable it to create .nca file.

### Steps to reproduce

Auto Save Lanuch Mode>No Save slot
Then game can't save.

### Expected behavior

I think it only work on autosave state, not to ram.

**Comment by Rakashazi** [comment]
This is the expected behavior for the "No Save" slot since it doesn't store a state or backup RAM (.sav, .srm, etc.). I've added a note about it on the Online Documentation to make it more clear. If you want only backup RAM but no state then you still need a save slot so try these settings:

- Autosave Launch Mode -> Main Slot (No State)
- Autosave Content -> Only Backup RAM

**Comment by leoxxx** [comment]
I see.
