### ISSUE TITLE
[Issue]: Disabling 'Skip Late Frames' no longer yields any changes

### ISSUE THREAD

**Issue by Code-Otto** [Rakashazi/emu-ex-plus-alpha#1381]
### Describe the bug

I like testing new software releases in rather old devices before updating them in my main one to make sure there's no big performance regressions in them. It's easy to overlook such issues while on a powerful device which can handle them anyways... whatever, you already know how much of a picky person I'm about this lol

Not a performance regression, but spotted what seems to be a breakage of the ability to deactivate the 'Skip Late Frames' feature

After commit d995ef72bdf70dbb7044c7b33073202fedb667c9 up to the latest version, this is what I get by tweaking the setting:

https://user-images.githubusercontent.com/129909770/234233797-f5a253a8-4cb6-47a7-9748-5c4422aff0d5.mp4

PS: the new automatic on-screen control placement layout doesn't adapts very well to tiny resolution screens as you may see. Not a big deal since it can be edited anyways

PS x2: The glitched text you see at the end of the video appears to be a common bug. I can reproduce it in my main device too by going into the Video options menu, locking the screen then turning on again and scrolling around

### Steps to reproduce

Fire up some old and relatively slow Android device and disable 'System > Video > Skip Late Frames'

### Expected behavior

This is the result of doing the same at version a6ef624a972a17945524ec8f5caa30d7c43e655b

https://user-images.githubusercontent.com/129909770/234233967-98018114-35f2-4f2c-a647-c4b9c0e27119.mp4

**Comment by Rakashazi** [comment]
Thanks for catching this. The emulation thread needs some additional logic to limit its frame skip when this option is on but also needs to know when you mean to fast forward so I need to do some tweaking there. I'm also implementing the updated "Target Frame Rate" option I mentioned previously that will allow a fixed frame skip to save power and also interacts with this issue so I'll roll in all the changes into the next commit.

**Comment by Code-Otto** [comment]
Commit 401d412 solved the issue, however fast forward is now not functional when 'Skip Late Frames' is set to Off
My extra-slow device here may not be the best example, but notice how at 0:20 I toggle fast forward without any effects. Can also reproduce at my main device

https://user-images.githubusercontent.com/129909770/234656093-bfe8928f-d08d-4084-bfc6-dcd7211dcc3f.mp4

However if 'Skip Late Frames' is set to Off and 'Target Frame Rate' is set to anything else than Full, there appears to occur some fast-forwarding in an odd way. Try mixing the values of both options to check out the various outcomes yourself

PS: I see there's been some refactoring and now the 'Reduce Compositor Lag' option which I liked to turn off is gone. Performance still looks pretty great as it used to in latest commits however I'd like to make a more in-depth analysis about it. What would be the proper way for me to reach out to you with the results? I'm unsure if that's worthy of opening a new issue here
Thank you!

**Comment by Rakashazi** [comment]
Ok, the "Skip Late Frames" option doesn't really make sense when you're not targeting a full frame rate so I really should combine it into the "Target Frame Rate" menu as "Full (No Skip)" to simplify things. About fast forwarding, I accidentally broke it by checking the wrong variable so that will also be fixed in the next commit.

I forgot to mention it before but I fixed a possible issue where the font cache isn't restored properly coming back from suspend. Are you still getting the missing letters on the current commit?

About "Reduce Compositor Lag", it selects whether to send a time stamp along with the current frame after it's rendered so the compositor can decide when to display it. It reduces lag in the sense that if the compositor itself were to fall behind its frame updates, like if you rotate the device and it has to do a lot of computations at the same time, the next frame is dropped instead of queued to keep the app in sync and not introduce an extra frame of input delay. This function is now used by the "Target Frame Rate" option to manage frame pacing, like when running a 60fps game at half rate it'll tell the compositor to show each frame in 33ms intervals, even if some frames finish rendering early and would appear after 16ms instead.

**Comment by Code-Otto** [comment]
Fast forwarding works again properly under any configuration with the latest commit. Can't seem to be able to reproduce again the font cache issue either

Interesting insight on the "Target Frame Rate" internals. I'll reevaluate the frame drops experienced while ingame in the latest emulator version in comparison with my new sweet spot (version v1.5.71) and open a new issue if I find any notable regression
I see a lot of huge changes going on, crossing my fingers for the new GCC 13 not to be producing slower code behind the scenes otherwise I'll finally go insane now lol

Thank you!
