### ISSUE TITLE
[Issue]: Performance regression since 401d412 in the BQ tenshi

### ISSUE THREAD

**Issue by Code-Otto** [Rakashazi/emu-ex-plus-alpha#1386]
### Describe the bug

Been evaluating the performance of commit d995ef7, version 1.5.71 and 1.5.72 as a comparison of versions past the 'big fix'
Found out 1.5.71 performs slightly worse than d995ef7 (may just be environmental noise in my tests), then 1.5.72 much worse than 1.5.72

First compared said three versions with my best known settings for them

https://user-images.githubusercontent.com/129909770/235801643-9264cbe4-1bfe-4da1-bd5b-d20f7247ba7b.mp4

Then compared 1.5.71 with 'Reduce Compositor Lag' On/Off and to 1.5.72 to test how much of the issue is introduced by the new forced reliance on the device's compositor frame discarding

https://user-images.githubusercontent.com/129909770/235802671-138841e6-67df-467d-befe-d5105d7e1f08.mp4

Sending in frame timestamps for the compositor to decide whether display frames appears to make a huge negative performance drawback in this device
It'd be nice for the Reduce Compositor Lag' option to come back if possible, even if just taking effect while the target frame rate setting is set to one of the 'Full*' modes

Thank you

### Steps to reproduce

I understand this is not easy without owning an actual BQ Aquaris U Plus for testing...

### Expected behavior

-

**Comment by Rakashazi** [comment]
Thanks for the report, just be 100% sure, this APK is the current commit with the call to set presentation time commented out. Does it run more like 1.5.71?

https://drive.google.com/file/d/1BLGAgMKGDcPzPlzOFUS_ie_7wHMWjajx/view

**Comment by Code-Otto** [comment]
Yes, the provided APK runs like 1.5.71, I may even say a little bit better!

https://user-images.githubusercontent.com/129909770/236268875-958f081b-796f-445e-a247-f16f2b0bb04f.mp4

**Comment by Rakashazi** [comment]
Ok, let's try only setting the presentation time if the frame will meet the screen's [deadline](https://developer.android.com/reference/android/view/Display#getPresentationDeadlineNanos()). How does this APK run?

https://drive.google.com/file/d/14mm0Axmh2q_59HDClR1Mex7pz-BqWePT/view

**Comment by Rakashazi** [comment]
Actually, try this APK instead. I re-enabled the frame time stats display and added some additional values of interest on top that I'd like to get a screenshot of from your device. This one also adds a 1ms offset to the presentation time since it seems Google's frame-pacing library does something similar.

https://drive.google.com/file/d/1k2tM1whP2fRRiXJF6409SuEeYp-Ak8UB/view

**Comment by Code-Otto** [comment]
Tested both APKs as I see from the Nvidia Shield Tablet issue last one made a big difference

https://user-images.githubusercontent.com/129909770/236649748-e22ac85a-df99-4542-b7e7-d4c3580e0c7e.mp4

Version 2023.05.05-test1 produced no noticeable differences compared to 2023.05.04-test1
However 2023.05.06-test1 introduced again some clear frame dropping issues

**Comment by Rakashazi** [comment]
Thanks for the comparison, I didn't realize the deadline time could be equal to or greater than the screen's frame time and that may explain the dropped frames when using presentation time. Try this APK and let me know which test version it's closest to.

https://drive.google.com/file/d/1sJSY5acoeeuC5wOx4IC7mSJTQ583AAXm/view

**Comment by Code-Otto** [comment]
This new 2023.05.07-test1 version appears to work better, however there's still a frame being skipped at a seemingly constant  time interval

https://user-images.githubusercontent.com/129909770/236681348-9e15fea4-f464-4d2b-8643-0180fb2e494d.mp4

In the slide down 1/10 speed part, notice how the 'curtain' at version 2023.05.07-test1 appears to fall behind the good reference one (2023.05.04-test1) then drops a frame and catches up for a moment (this can be noticed twice during said animation)

Thanks for all the attention you're putting at this issue!

**Comment by Rakashazi** [comment]
No problem, I found an alternate way to prevent frames from getting queued by using eglSwapInterval(0) which normally disables v-sync but on Android it works differently and is similar to what I was doing setting the presentation time, so now I only need to set it when not running at a full target frame rate. This new method was force-enabled in the last build but I've made a new APK with the "Present Mode" option under Video -> Advanced to configure it.

About the dropped frames when setting presentation time, the compositor on that device is configured to hold queued frames longer than the Pixel I'm testing on that has a deadline time of 11ms. As a result, depending on when the compositor wakes up to latch the next frame compared to when the app is rendering, the app may have multiple frames rendered and the compositor only picks up the most recent on due to checking the presentation time on each frame, causing a sort of "frame skip" but at the compositor level and not the app. Now with the "Present Mode" option set to "Queued", check if you get the exact same behavior from the older versions with "Reduce Compositor Lag" set to off.

https://drive.google.com/file/d/1G5I5_LdSp2kldfaLPuJ4D46CgWn-5Ak6/view

**Comment by Code-Otto** [comment]
This new version appears to perform better than 2023.05.07-test1 did, but the 'catching up curtain' detail I previously described seems to still occur here, evidencing some eventual frame skips (notice them again during the x1/10 part) 
However, I can't seem to be able to notice by eye said skips now while playing on the device's screen. Either I'm today having a bad carelessness day :laughing: or the issue is only present at the video capture but not the device's screen

https://github.com/Rakashazi/emu-ex-plus-alpha/assets/129909770/03496626-dafe-4b78-bac3-1f87832d5ff7

Also included the poor results obtained with 'Immediate' mode at my device for completeness sake. Tested both Present Modes with Image Buffers set to 2 as well, without it bringing any improvement

I'll try to take a closer look into the frame skip issue by eye and attempt to determine as much as I can whether the issue is actually present at what's displayed in the device's screen. If I have to push my senses like this just to notice maybe the issue is no longer that bad... Anyhow, this seems like a big step forward. Thanks for your hard work!

Is there anything preventing presentation timestamps from being toggleable via a video settings option as it used to? Version 2023.05.04-test1 seemed to do pretty well on my device, even the different 'Target Frame Rate' modes seemed functional

**Comment by Code-Otto** [comment]
Been further testing and yes, the eventual frame skips are still there and could notice them by eye on the device's screen by looking very closely for them
This last update seems to have certainly brought some improvement though. The issue seems pretty much a minor thing now as I have a hard time managing to even notice it

**Comment by Rakashazi** [comment]
Thanks for the testing as always, hopefully this last commit will cover everything:
* Immediate present mode is now always an opt-in option
* Added the new "Precise Frame Pacing" option which is the equivalent of "Reduce Compositor Lag" but was renamed since presentation time now is only used for frame pacing when the frame rate target isn't full
* Sync fences were re-added to the Image Buffers == 1 case for correctness, shouldn't cause any additional performance issues

**Comment by Code-Otto** [comment]
Hi! Didn't yet get the time to do the comprehensive testing however I've given Tekken Advance a quick try and the flickery shadow has proven indeed extremely useful at making frame drops very noticeable by eye

I can now fully confirm the video capture introduces some frame drops and that the latest version has fully solved the regression this issue was initially opened for. Now latest and 1.5.71 behave similarly again
With this new game I've however noticed there's still some eventual frame drops (just one each few seconds) happening both in 1.5.71 and the latest version in a similar fashion

Will mark this issue as closed and should I find another regression or when I gather some more details about this remaining sparse frame drop problem I'll get back here with a new issue

Thanks for all your attention!
