### ISSUE TITLE
Add Snes9x EX+ core 1.60

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#139]
Hi @Rakashazi, some time a go I updated the Snes9x EX+ core to 1.60, is it okay to send it over to you or open a Pull Request to add the changes?

**Comment by Rakashazi** [comment]
Sure, if you send the diff from the stock 1.60 Snes9x I'll look it over for integrating into the next release. Thanks.

**Comment by bladeoner** [comment]
Hi @Rakashazi, I added the Snes9x stock 1.60 diff (snes9x.diff), and a additional file (snes9x_additional.diff) with the changes I made to make it work:
[snes9x.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4081981/snes9x.zip)

I also have a diff for the GBC.emu to fix an audio issue:
[gbc.emu.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4082002/gbc.emu.zip)

And I have a diff for the NES.emu to correct the palette colors and fix an audio issue:
[nes.emu.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4082013/nes.emu.zip)

**Comment by Rakashazi** [comment]
I just updated Snes9x EX+ to 1.60. Since the cheat system changed I ended up updating the code to use the new functions while still keeping compatibility with 1.43 instead of using the back-ported code in your patch, but thanks again @bladeoner for submitting it. I'll add the patches for GBC.emu and NES.emu when I do updates for those cores soon.
