### ISSUE TITLE
Unable to navigate to internal storage on Android 10

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#140]
I'm using a Huawei P Smart 2019 phone (Kirin 710, Android 10, not rooted) with MD.emu 1.5.40. In addition to the internal storage an SD card is installed. It is not possible to navigate to the internal storage, but external (SD card) storage works OK.

At the main menu, touch Load Game. Touch the top bar to show File Locations menu. Three items are shown:
- Storage Media
- Storage Devices
- Root Filesystem

Touching Root Filesystem attempts to show the root directory (/), says "Can't open directory: Permission denied". That's probably as expected on a non-rooted device.

Touching Storage Media shows files on the external SD card.

Touching Storage Devices shows a menu with three items:
- 0123-4567
- emulated
- self

Touching 0123-4567 again shows files on the external SD card ("Storage/0123-4567" in header bar at top).

Touching emulated or self shows this text in a red bar at bottom of screen:
"Can't open directory: Permission denied"
(The way that text is presented differs from the "Root Filesystem" case described above.)

So, while the external SD card can be reached in two ways, the internal storage cannot.

By way of comparison, I can use [ZArchiver](https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver) to navigate both internal and external storage. In ZArchiver, on touching the directory name shown at top of screen, it shows a menu with these entries:
 - Device memory
   /storage/emulated/0
 - SD card
   /storage/0123-4567
 - Download
   /storage/emulated/0/Download
 - Music
   /storage/emulated/0/Music

So the problem seems to be that MD.emu is trying to show files in directory /storage/emulated which is not allowed. (/storage/emulated/0 is allowed.)

Perhaps letting the user manually type a complete path could allow issues like this to be worked around?

**Comment by Rakashazi** [comment]
It looks like on this device the SD card is getting returned as the primary shared storage path instead of the internal storage. There should be a way to enumerate storage volumes on recent versions of Android so I'll research this and see if I can include something in the next update to handle this case.

**Comment by M-a-r-k** [comment]
Some more information. I had originally used the phone without SD card, then installed SD card and set default storage location to memory card (Settings->Storage->Default location).

I just changed the default location back to internal storage (which required the phone restart). I launched Snes9x-EX+ 1.5.40. Now touching Storage Media shows the phone internal storage and touching Storage Devices then 0123-4567 shows the SD card. Touching emulated or self still shows the permission denied message.

**Comment by Rakashazi** [comment]
Thanks for the update, that's the expected behavior as there's always a single storage path set as the primary one exposed by the app as Storage Media. I looked into the Android StorageManager class and found a way to get the paths of all mounted storage volumes on Android 7.0+ so that eliminates the need for the Storage Devices entry. With the next app update it will just list all the storage volumes directly under Storage Media so there won't be any issues with listing the contents of /storage/*.
