### ISSUE TITLE
Request: GBC.emu - Super Gameboy colors

### ISSUE THREAD

**Issue by Toni22** [Rakashazi/emu-ex-plus-alpha#173]
Is it possible to add the super gameboy colors for old gameboy games in GBC.emu? I don't need the borders from the super gameboy, but the ingame colors are different to the gbc-colors.

**Comment by Rakashazi** [comment]
I've done some research on this and it looks like the SGB features are all handled on the SNES side by sending commands to a program rom on the SGB SNES cart, so it's beyond the scope of GBC.emu. However, I'll leave this open since it may be possible to simulate the SNES SGB program similar to how high-level BIOS emulation is implemented in other emulators but it will require more research and testing.

**Comment by SopTheSop2022** [comment]
Super Game Boy System, Palettes Are Supported On VGBA, mGBA. mGBA Is BETTER BECAUSE All Games Work.

**Comment by SopTheSop25** [comment]
Better To Update Core To mGBA 0.9.3 On GBC.emu & GBA.emu And Add

**Comment by SopTheSop29** [comment]
https://github.com/snes9xgit/snes9x/issues/758

**Comment by CraftFan22** [comment]
mGBA 0.10.0 Is Released.

**Comment by Squidward22** [comment]
#407
