### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#191]
@Rakashazi I hope you are doing fine.

I got a question, since the latest change I'm seeing the warnings below.
The build is still running fine, but do you have an idea by what it is caused and do you also see it in your environment?

warning: unknown warning option '-Wno-non-c-typedef-for-linkage'; did you mean '-Wno-return-type-c-linkage'? [-Wunknown-warning-option]

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks for the report and hope you're doing fine as well. This is a new option added in Clang 11 that causes a warning when used in the older version included in NDK 21. I've now tested NDK 22 and found it stable to use so I'm updating the minimum NDK version in the next commit. Please install the latest NDK 22.0.6917172 and that will resolve the warning messages. Remember to clean all compiled .o files after upgrading since it's a major compiler update.

**Comment by bladeoner** [comment]
@Rakashazi thank you for your quick response that seems to do the trick, using NDK 22.

I also wanted to let you know I'm busy creating a Github Workflow, a CI solution that when you check in your code a docker container will spin up and build the code as an extra check.

**Comment by Rakashazi** [comment]
Thanks, good luck and let me know how it turns out.
