### ISSUE TITLE
[libarchive]build error: macros - cannot combine with previous 'int' declaration specifier

### ISSUE THREAD

**Issue by BlueMax** [Rakashazi/emu-ex-plus-alpha#197]
I try to compile armv7 on Arch Linux 5.10.4 and get the error below. It did work properly before (maybe a year ago). Looks like something is wrong with the macros.

Any ideas?

```
emu-ex-plus-alpha/imagine/bundle/all $ ./makeAll-android-armv7.sh
[...]
checking for uintmax_t... no
checking for unsigned long long... no
checking for unsigned long long int... yes
checking for long long int... yes
checking for intmax_t... no
checking for uintmax_t... (cached) no
checking for int64_t... no
checking for uint64_t... no
checking for int32_t... no
checking for uint32_t... no
checking for int16_t... no
checking for uint16_t... no
checking for uint8_t... no
checking how /tmp/JD2/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/clang reports undeclared, standard C functions... configure: error: in `/tmp/imagine-bundle/libarchive/build/android-armv7':
configure: error: cannot compile a simple declaration test
See `config.log' for more details
make: *** [common.mk:49: /tmp/imagine-bundle/libarchive/build/android-armv7/Makefile] Error 1
```

The corresponding `config.log` is [here](https://gist.github.com/BlueMax/36ef9e87a4d9454c22fb72ad9c698737/raw/3f521564131a432e5075ef813b04050d64542b36/config.log).
If i override the check with `./makeAll-android-armv7.sh ac_cv_c_decl_report=no` i get [this](https://gist.github.com/BlueMax/36ef9e87a4d9454c22fb72ad9c698737/raw/3f521564131a432e5075ef813b04050d64542b36/compile.log) on stdout.

Environment:
```
export IMAGINE_PATH=~/android/emu-ex-plus-alpha/imagine
export IMAGINE_SDK_PATH=~/android/emu-ex-plus-alpha-build/imagine-sdk
export ANDROID_SDK_ROOT=~/android/android-sdk
export ANDROID_NDK_PATH=/tmp/JD2/android-ndk-r22
export CROSS_COMPILE=arm-linux-androideabi
export android_arch="armv7"
export PATH=${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
```
Android SDK:
```
$ sdkmanager --list
Installed packages:=====================] 100% Computing updates...             
  Path                        | Version | Description                             | Location                    
  -------                     | ------- | -------                                 | -------                     
  build-tools;29.0.2          | 29.0.2  | Android SDK Build-Tools 29.0.2          | build-tools/29.0.2/         
  build-tools;30.0.3          | 30.0.3  | Android SDK Build-Tools 30.0.3          | build-tools/30.0.3/         
  cmake;3.10.2.4988404        | 3.10.2  | CMake 3.10.2.4988404                    | cmake/3.10.2.4988404/       
  cmdline-tools;latest        | 3.0     | Android SDK Command-line Tools (latest) | cmdline-tools/latest/       
  emulator                    | 30.2.6  | Android Emulator                        | emulator/                   
  extras;android;m2repository | 47.0.0  | Android Support Repository              | extras/android/m2repository/
  patcher;v4                  | 1       | SDK Patch Applier v4                    | patcher/v4/                 
  platform-tools              | 30.0.5  | Android SDK Platform-Tools              | platform-tools/             
  platforms;android-29        | 5       | Android SDK Platform 29                 | platforms/android-29/       
  platforms;android-30        | 3       | Android SDK Platform 30                 | platforms/android-30/       
  tools                       | 26.1.1  | Android SDK Tools 26.1.1                | tools/
```

**Comment by bladeoner** [comment]
@BlueMax most of the time this kind of errors is because the NDK path is not defined correctly or the NDK version does not exist in the defined path.

What I would suggest is:
- Define the NDK dir under the SDK dir for example:
export ANDROID_NDK_PATH=~/android/android-sdk/ndk/android-ndk-r22
- Download and extract the android-ndk-r22 to ~/android/android-sdk/ndk it should automatically create the android-ndk-r22 folder.
Download link: https://dl.google.com/android/repository/android-ndk-r22-linux-x86_64.zip

**Comment by Rakashazi** [comment]
It does look like an NDK installation issue since those int type tests (int64_t, int32_t, etc.) shouldn't fail. You may also remove these unneeded environment variables:
```
export CROSS_COMPILE=arm-linux-androideabi
export PATH=${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
```

**Comment by BlueMax** [comment]
I don't want to disagree. NDK setup should be handled by the `build system` though (beside `ANDROID_NDK_PATH`).
Other packages (libogg, libsndfile, tremor, xz) don't seem to have problems and compile properly beforehand when doing `./makeAll-android-armv7.sh`. It might be something specific with `libarchive` i guess. The `autoconf` looks somewhat messy. The full log of `./makeAll-android-armv7.sh` is [here](https://gist.github.com/BlueMax/36ef9e87a4d9454c22fb72ad9c698737/raw/8d69696b3566b8985e5683a8acfd7877835971d6/makeAll-android-armv7.sh).

@Rakashazi: 
Are you still on Gentoo? Are we somewhat in the same boat (same versions) regarding autotools?
Kernel 5.10.4
autoconf 2.70
automake 1.16.2
m4 1.4.18
libtool 2.4.6+42+gb88cebd5

**Comment by Rakashazi** [comment]
@BlueMax Ok, thanks for the clarification. I thought it was a general problem with all the autoconf packages but since it's only happening with libarchive I tested it out on autoconf 2.70 and it indeed fails as you mentioned. I re-tested on the latest libarchive 3.5.1 and same issue so it looks the configure script isn't yet compatible with 2.70. On Gentoo, autoconf 2.70 is currently masked due to some packages failing to build with it so the default is 2.69.

If you can install different versions of autoconf at once like Gentoo, the makefile now checks specifically for "autoconf-2.69" and falls back to "autoconf" when missing. If not, you'll have to downgrade the system autoconf to 2.69 for the libarchive build. It's safe to upgrade back to 2.70 after since autoconf is only used for building the bundled libraries.

I'll keep this issue open until either the build is fixed with autoconf-2.70 or I switch to using the cmake build instead which shouldn't have this issue.

**Comment by BlueMax** [comment]
Confirmed. Works here as well. Thanks!

**Comment by JuanVCS** [comment]
https://github.com/libarchive/libarchive/pull/1481

**Comment by Rakashazi** [comment]
Thanks, added a patch and tested building on Autoconf 2.71 with no issues.
