### ISSUE TITLE
Nightly builds using github actions

### ISSUE THREAD

**Issue by strikersix23** [Rakashazi/emu-ex-plus-alpha#201]
Can you provide nightly builds using github actions

**Comment by bladeoner** [comment]
@Rakashazi if you want to provide nightly builds I can make the adjustments to the current Github Workflow and send you the changes.

**Comment by Rakashazi** [comment]
Sure, go ahead and send the changes when they're ready.

**Comment by bladeoner** [comment]
@Rakashazi I got it, attached are the changes required:
[add_nightly_build.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/5939179/add_nightly_build.zip)

There is one extra step required to make the build consistent, otherwise it will use a new debug.keystore everytime a build is triggered:
- First you need to get the debug.keystore value on your own linux machine by using the following command:
base64 --wrap=0 .android/debug.keystore > encodedData.txt
The encodedData.txt will containt a large string which will be needed in the next step.
Please be aware you cannot see the secret again after it has been entered in Github, it can only be updated.
- Go to your Github profile click on the "emu-ex-plus-alpha" branch , go to Settings, go to Secrets and add the following secret:
Name: DEBUG_KEYSTORE
Value: *Paste encodedData.txt value here*

**Comment by strikersix23** [comment]
the APP bundle isn't useful because its compiled with a release keystore not debug not just that its not installable on native device.  I think using bundletool on github actions generating an apk using debug keystore and then ziping the folder for upload would allow a large number of users not just developers

**Comment by bladeoner** [comment]
The build is compiled with a debug keystore.
The build.gradle file is replaced during the Github Workflow by the one in the .github/workflows/ folder and the changes I attached retrieves the debug.keystore secret.

The fact that the output is an Bundle file is because it is defined in the source code, the Github Workflow doesn't change that, it is just compiling source.

**Comment by strikersix23** [comment]
I wonder if it is possible that a script can be used to split the app bundle of apk and send them to a specific folder zip and upload

**Comment by bladeoner** [comment]
I think applying a patch in the Github Workflow would compile the apk files.

In my own build I changed line 7: imagine/make/shortcut/meta-build/android.mk

Current value: all : android-bundle
New value: all : android-apk

This generates the apk files.

**Comment by bladeoner** [comment]
@strikersix23 I wrote two patches the files are debug APK files and can be downloaden here:
https://github.com/bladeoner/emu-ex-plus-alpha/actions/runs/555705321

@Rakashazi I have updated the links and the diff today in my second post, when you have time you can add that to enabled the Nightly Builds.

**Comment by strikersix23** [comment]
It works fine appreciate it

**Comment by Rakashazi** [comment]
@bladeoner Thanks, I've added the changes needed for nightly builds. In case of any updates just let me know.

**Comment by bladeoner** [comment]
@Rakashazi I will let you know.

**Comment by strikersix23** [comment]
@bladeoner. Can I have your help on a workflow for one of my projects.
