### ISSUE TITLE
No SD Card access in Android 11

### ISSUE THREAD

**Issue by IdiotBlueMage** [Rakashazi/emu-ex-plus-alpha#205]
This seems to be an issue with a lot of emulators on the platform lately: a change in how Android manages storage or something similar caused a lot of apps to be unable to even see the SD Card directory.  It seems that .Emu apps are no exception.

A current workaround is to use a frontend such as Dig or ARC Browser, most of which have fixed this issue.  The only emulators I know of that have this problem fixed are Dolphin (partially) and Duckstation.

**Comment by Rakashazi** [comment]
Thanks for the report, it looks like external storage is more locked down on Android 11 so I'll have to implement support for scoped storage. I'm currently looking into the best way to do this since it's quite a significant change to how files are accessed in the app.

**Comment by tokariu** [comment]
I have similar issues. for example, Snes 9x EX+ unable to open ROM files from the external SD Card. It lacks permissions to read from my custom dirs and further lacks permission to write on it.

the issue is the same on other emulators, like the GBC.emu.

Android 11 changed the way apps need to request storage permission with the introduction of scoped storage. it's a mess for all older apps that used to store data on ext. sdcards.

unfortunately there doesn't seem to be a working fix around like using magisk and something like ExSDcard module, which made the ext.SDcard writeable on android <= v10. This workaround stopped working in Android 11.
Android 11 forces the new restrictions.
All these Apps need updating. There seems to be no way around it.

**Comment by Rakashazi** [comment]
I made a test a implementation of scoped storage mode but unfortunately it can't cover all use cases like loading files referenced by other files (.cue disc images, MSX Bios ini files, etc), so I'm not adding it for now. On the plus side, I did find a new function added in Android 11 to get the full path of a storage volume and restore SD cards appearing in the file locations menu since /storage isn't accessible. Give this debug Snes9x EX+ APK a try and let me know if your SD card is accessible.

https://drive.google.com/file/d/1W3GmwoihYyc7nVxuxK-4VULoozkCpbsj/view

**Comment by tokariu** [comment]
> I made a test a implementation of scoped storage mode but unfortunately it can't cover all use cases like loading files referenced by other files (.cue disc images, MSX Bios ini files, etc), so I'm not adding it for now. On the plus side, I did find a new function added in Android 11 to get the full path of a storage volume and restore SD cards appearing in the file locations menu since /storage isn't accessible. Give this debug Snes9x EX+ APK a try and let me know if your SD card is accessible.
> 
> https://drive.google.com/file/d/1W3GmwoihYyc7nVxuxK-4VULoozkCpbsj/view


@Rakashazi I tested this preview version and so far it seems to work like a charm. I mean, the "OS Path Picker" works great, and it is the only way that works (the others like "custom path", "root filesystem", etc won't work for ext.sdcards). This method seems to be solid, you can select a custom folder on the ext.sdcard and android v11 asks for permission for exactly this folder. After that, all ROMs are loadable from the ext.SDcard. Even the .cht files and save-state files in that same folder work. (didn't test .cue or msx bios ini files etc though)

One thing still needs a little adjustment: the way to find the "OS Path Picker". When I first choose "Load Game" I'm somewhere stuck in the old file menu and it is not clear where to find the "OS Patch Picker" option. I just found it by accident by clicking on the top left of the folder-listing until I was at the top level.

so.. it actually works. would love to have it in all the other emus too. a little finetuning to access the new option and it's good to go!

**Comment by Rakashazi** [comment]
@tokariu Thanks for the feedback, I've added a message about selecting a new path from the top bar if the file picker is stuck in a directory without read permission. These changes will all be rolled into the upcoming 1.5.52 release.
