### ISSUE TITLE
GBA.emu update core

### ISSUE THREAD

**Issue by android-1995** [Rakashazi/emu-ex-plus-alpha#214]
In the v1.5.51 version, some games will freeze.  I uploaded some games, you can try.

**Comment by android-1995** [comment]
[口袋妖怪改版_命运红宝石3生命守护者_汉化版.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512540/_.3._.zip)
[口袋妖怪命运红宝石2汉化版.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512541/2.zip)
[萌娘鹿汉化版v1.5.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512542/v1.5.zip)
[骑拉帝纳的逆袭汉化版v2.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512543/v2.zip)
[燃烧红宝石汉化版.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512544/default.zip)
[后宫战记.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512545/default.zip)
[剑盾铠之孤岛修复汉化版.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6512546/default.zip)

**Comment by IdiotBlueMage** [comment]
Alright, this is from testing the top version.  These files do appear to be zipped roms, handle the situation as you see fit but I'm attempting to get to the bottom of exactly what this is.  Looking up the title on google translate tells me this is a chinese version of a Pokemon Ruby romhack named Ruby Destiny: Life of Guardians.  After doing a bit of research, the patch is found here but the BPS isn't made for any ROM I have: http://chinesetranslationsandromhacks.blogspot.com/2018/06/gba-pokemon-ruby-destiny-3-life-of.html

This barely even boots on all GBA emus.  I honestly think this is not the emulator's fault and someone just patched the wrong file instead; after ignoring checksums with my version of Ruby, I ended up with the same result.  But like I said before I don't really have anything to test it against.

**Comment by android-1995** [comment]
> Alright, this is from testing the top file. These files do appear to be zipped ROMs, handle the situation as you see fit but I'm attempting to get to the bottom of exactly what this is. Looking up the title on google translate tells me this is a chinese version of a Pokemon Ruby romhack named Ruby Destiny: Life of Guardians. After doing a bit of research, the patch is found here but the BPS isn't made for any ROM I have. It doesn't tell you much about what to patch it to either: http://chinesetranslationsandromhacks.blogspot.com/2018/06/gba-pokemon-ruby-destiny-3-life-of.html
> 
> This barely even boots on all GBA emus. I honestly think this is not the emulator's fault and someone just patched the wrong file instead; after ignoring checksums with patching my version of Ruby, I ended up with the same result. But like I said before I don't really have anything to test it against.

Thank you for your answer. These are modified version of the game files, but they can run normally in [My Boy! ](https://play.google.com/store/apps/details?id=com.fastemulator.gbafree&hl=en_US&gl=US). So I am not sure if it is a problem with the simulator.

**Comment by IdiotBlueMage** [comment]
> Thank you for your answer. These are modified version of the game files, but they can run normally in [My Boy! ](https://play.google.com/store/apps/details?id=com.fastemulator.gbafree&hl=en_US&gl=US). So I am not sure if it is a problem with the simulator.
I see!  I apologize then, since it runs on something I didn't test.  It's completely possible that the hack just exploits old emulator flaws and it wasn't tested on much else, which means you'll have to stay with My Boy! for those specific files.

A lot of times, very old romhacks can require a specific emulator because they exploit specific flaws in that emulator, and they can't even run on the actual hardware.  There are some very old Super Mario World hacks that only work properly on ZSNES for example.  If I had a GBA flashcart on hand, I would test to see if this would work on an actual GBA.  That would confirm what I'm thinking.

**Comment by Helloworld996** [comment]
> > 谢谢您的回答。这些是游戏文件的修改版本，但可以在“[我的男孩”中](https://play.google.com/store/apps/details?id=com.fastemulator.gbafree&hl=en_US&gl=US)正常运行[！](https://play.google.com/store/apps/details?id=com.fastemulator.gbafree&hl=en_US&gl=US)。所以我不确定模拟器是否有问题。
> 
> 我懂了！抱歉，因为它在我未测试的东西上运行。该黑客很有可能只是利用了旧的模拟器缺陷，并且没有经过其他方面的测试，这意味着您必须与My Boy呆在一起！对于那些特定的文件。
> 
> 很多时候，非常老的romhack可能需要特定的仿真器，因为它们在该仿真器中使用特定的缺陷，甚至无法在实际的硬件上运行。例如，有些非常古老的《超级马里奥世界》骇客仅能在ZSNES上正常工作。如果我手上有一个GBA闪存卡，我会测试一下是否可以在实际的GBA上使用。那将证实我的想法。

**Comment by Helloworld996** [comment]
> > Thank you for your answer. These are modified version of the game files, but they can run normally in [My Boy! ](https://play.google.com/store/apps/details?id=com.fastemulator.gbafree&hl=en_US&gl=US). So I am not sure if it is a problem with the simulator.
> 
> I see! I apologize then, since it runs on something I didn't test. It's completely possible that the hack just exploits old emulator flaws and it wasn't tested on much else, which means you'll have to stay with My Boy! for those specific files.
> 
> A lot of times, very old romhacks can require a specific emulator because they use specific flaws in that emulator, and they can't even run on the actual hardware. There are some very old Super Mario World hacks that only work properly on ZSNES for example. If I had a GBA flashcart on hand, I would test to see if this would work on an actual GBA. That would confirm what I'm thinking.

**This emulator is very good. But unfortunately, compatibility is a bit inadequate. 
In the above games, not only myboy but also pizza boy or John simulator can run normally. 
But gba.emu There are 2 suspended operations during combat. 
The other five games are paused at the start of the game. 
I hope it can be repaired. (emulator version of the test:gba.emu 1.5.51). 
The 'happy Chick' emulator also uses gba.emu, but it can run these games properly.I don't know why. 
Maybe they changed it. 
Happy chick app: 
Https://happy-chick.en.uptodown.com/android. 
"剑盾铠之孤岛修复汉化版.gba" and "后宫战记.gba" will stop in battle, unable to carry out any operation." 
Other games will stop at the beginning.
I really wish you could fix there probelm,alothough i can play in antoher emulator,but i like gba.emu.because it has Multiple filter shaders。**

**Comment by bladeoner** [comment]
@android-1995 can you try attached build to see if the Pokemon games you are trying to play are working?

[GBAemu.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7269382/GBAemu.zip)

Thanks in advance.

**Comment by IdiotBlueMage** [comment]
This is a shot in the dark, but maybe if we let the BIOS file be used it would fix these?  I didn't really realize this until later on but more accurate emulators both in the store and out also need the BIOS file to make some games work properly.  That would mean GBA.emu would need it even moreso, but we don't have the option.

**Comment by bladeoner** [comment]
@Helloworld996 I'm building another file takes more or less 15 minutes, could you try again when it is finished?

**Comment by bladeoner** [comment]
It just finish compiling, can you see if it makes any difference?

I also tried adding the option in the code to see if iit needs the BIOS or not, there is only one game that needs the BIOS as far as I can see and that is "Yu-Gi-Oh! GX - Duel Academy (USA)", none of the Pokemon games.

[GBAemu_test2.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7269830/GBAemu_test2.zip)

**Comment by Helloworld996** [comment]
> It just finish compiling, can you see if it makes any difference?
> 
> I also tried adding the option in the code to see if it needs the BIOS or not, there is only one game that needs the BIOS as far as I can see and that is "Yu-Gi-Oh! GX - Duel Academy (USA)", none of the Pokemon games.
> 
> [GBAemu_test2.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7269830/GBAemu_test2.zip)

Test that the above games are still stuck. 
Every one of them has been tested. 
If you want to test at any time, you can download "口袋妖怪命运红宝石2汉化版.zip" for testing. The game download address is on the second floor. 
Click on the text to download.
Because the game will get stuck at the beginning of the game.

**Comment by android-1995** [comment]
[GBA-thumb.cpp](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gba/GBA-thumb.cpp)
```
// MOV Rd, Rs
static INSN_REGPARM void thumb46_0(uint32_t opcode)
{
    reg[opcode & 7].I = reg[((opcode >> 3) & 7)].I;
    clockTicks = codeTicksAccessSeq16(armNextPC) + 1;
}
```
```
thumb46_0, thumb46_1, thumb46_2, thumb46_3, thumb47, thumb47, thumbUI, thumbUI,
```
fix  freeze
