### ISSUE TITLE
Gbc.emu Bios emulation?

### ISSUE THREAD

**Issue by EluxRed** [Rakashazi/emu-ex-plus-alpha#224]
Is there a way to load a bios file on gbc.emu? if yes, how?
i'd like to practice my manips for speedruns on android and i would need the bios screen (the one that says gameboy).. hopefully the emulator emulates the rng correctly, since it was made from gambatte, if i understand correctly

**Comment by IdiotBlueMage** [comment]
IIRC GBC.emu is based on Gambatte, and that one only really uses the BIOS for the bootlogos.  SameBoy does the same thing according to its creator, I don't know about bgb since it's closed source.

I'd actually like this function for GBA.emu even more though, because VBA-M most likely still finds use for it.
