### ISSUE TITLE
Link Cable in GBC.emu/GBA.emu

### ISSUE THREAD

**Issue by MM2WOOF** [Rakashazi/emu-ex-plus-alpha#229]
You know, your emulator by itself has a high precision, higher than other emulators but you urgently need the Link Cable because of all the emulators that are on Android, only one has Link Cable but it is not so precise and it lacks functions that your emulators have, I do not force the urgent implementation of the emulator but it would be a good idea.

**Comment by IdiotBlueMage** [comment]
I don't mean to adversise but that's actually not completely true, both Pizza Boy Pro emus can link cable and they use the dev's own code at the core.  Pretty much at GBC.emu's level minus one test as far as those go.

Anyway, GBC.emu only has Gambatte up to the original instead of keeping up with something like gambatte-speedrun.  I don't really know if that fork has anything useful for linking or not.

**Comment by rollingmoai** [comment]
There is currently no open-source GBA emulator for android that supports the Link Cable functionality.
