### ISSUE TITLE
[MD.emu] SRAM creates randomly on non-SRAM games

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#242]
Appernlty MD.emu makes SRAM files for games that don't have SRAM. This is weird considering that some Mega Drive/Genesis games don't have SRAM/Battery Backup in their cartridges (but some of the ones that have SRAM are RPGs and strategy games), so my advice is to remove the option for Big-Endian SRAM and make some saves compatible with all emulators. The real Genesis Plus GX doesn't have this problem, I think.

**Comment by Rakashazi** [comment]
Thanks for the report. Certain ROMs are assumed to have SRAM since the headers aren't always reliable and the app doesn't have an internal database. I've added a check to see if the SRAM is blank and skip writing the .srm file in that case. It'll also remove any existing blank .srm created for a game the next time you open and close it.
