### ISSUE TITLE
all emu in android 11 custom os, sound has delay.

### ISSUE THREAD

**Issue by Visntse** [Rakashazi/emu-ex-plus-alpha#255]
i use latest emu apk from github auto build.
my phone is xiaomi 6, use lineage os 18.1 official latest build rom.
only use root, nothing install any app.

but all emu sound delay.
i try to change many more emu sound or system setting, but problem still.
or use emu default setting, problem again.

so, what happent?
i can build emu apk use virtualbox, maybe you can tell me how to try or fix? or i try to test it?

my mother language is't engline, sorry for some language bad.

**Comment by Rakashazi** [comment]
Is this with the internal speaker or a bluetooth audio device? Many bluetooth devices don't support low latency audio and will introduce significant delays if used. Also, did you also try changing the audio driver between AAudio and OpenSL ES? If you get the same delay with both options then the issue is most likely a problem with the audio driver on your device and should be reported to Lineage OS instead.

**Comment by Visntse** [comment]
internal speaker.
aaudio and opensl both i try it.
so~okay..maybe i try run it again, when new system is out.

**Comment by Visntse** [comment]
hey, it's me again.
now i test again, oh... the problem is i use bluetooth audio.
i try to change aaudio or opensles, it's all delay.
internal speaker work fine.

so... i think it's all BT device's problem. but another app, like some movie app, it can be play video and audio synchronize, how it works?
or maybe i need change some emu setting? and change some phone system setting?
please tell me... thanks so much!

**Comment by Rakashazi** [comment]
Android can adjust movie playback to line up with the delayed audio so it looks like there's no delay, but this isn't possible for a game since the video & audio are generated based on your inputs. The Bluetooth latency is based on the audio device itself and the codecs it supports. Try to set different codecs in the Android settings app under Developer Options -> Bluetooth Audio Codec and see if it makes the delay better or worse.
