### ISSUE TITLE
Update New Overlays In NES.emu, Snes9x EX+, GBC.emu, GBA.emu, MD.emu, PCE.emu, C64.emu, MSX.emu, 2600.emu, NGP.emu, NEO.emu

### ISSUE THREAD

**Issue by SopTheSop27** [Rakashazi/emu-ex-plus-alpha#305]
### Describe the feature

Update New Overlays In NES.emu, Snes9x EX+, GBC.emu, GBA.emu, MD.emu, PCE.emu, C64.emu, MSX.emu, 2600.emu, NGP.emu, NEO.emu

### Add screenshots

NES.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159065712-e781dd0c-39d0-4123-8ae5-1bfa271693e9.png)
Snes9x EX+
![overlays128](https://user-images.githubusercontent.com/101358042/159065781-934c5f10-34ba-42cd-8f69-a69ede29a165.png)
GBC.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159065808-0d8cc53d-c08b-45dd-88eb-d06edbd3a4aa.png)
GBA.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159065874-3d0c6d21-9f3f-4dd7-a6c4-ae6d3f999859.png)
MD.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159065952-387ac2f5-975d-4c8d-a60a-6d3f5c58eff9.png)
PCE.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066031-53591458-035c-4a6f-b8f2-b0b33ef850dc.png)
C64.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066096-a76e723b-a47b-4a26-8fbc-7fcc936283e4.png)
MSX.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066142-92a29cf1-e1e9-4ebb-a640-5612a4294830.png)
2600.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066185-ce959042-b063-4e7c-ae2c-dd08dcd29c17.png)
NGP.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066240-64dbd3c3-5fbd-4d22-a8ff-7d7cdeb9c284.png)
NEO.emu
![overlays128](https://user-images.githubusercontent.com/101358042/159066301-32ccca56-f3e8-44b6-b8bb-4bb95a8da910.png)

Download New Overlays: https://drive.google.com/file/d/1-bSA5RYxtYPyM6J2xEfRjaWtXENKHSPR/view?usp=drivesdk

**Comment by master1274** [comment]
Skins are made in a very artisanal way. I know because I have a relationship with some of them (no complaints). I am the author of a black cross on a white background, colored buttons with white letters, and white L/R with black letters. Initially, the task was only about SNES overlay. It matches the actual color of the buttons SNES. The rest with the same buttons in the base do not match the real colors of the consoles. Made just for beauty. I repeat, the skins are made very handicraft. It was probably better to make an improvement request - Possibility to choose a third-party overlay skin.

**Comment by SopTheSop25** [comment]
It May Will Be On 1.5.60 Version Release
