### ISSUE TITLE
[Issue]: SNES9xEX cheat selection not persistent

### ISSUE THREAD

**Issue by noabody** [Rakashazi/emu-ex-plus-alpha#514]
### Describe the bug

Using SNES9x on computer, with properly formatted cheat file, I can see this difference between selected and un-selected cheats.
Not selected:

```
cheat
  name: Walk Through Walls
  code: c62f0e=60
```

Selected:
```
cheat
  name: Walk Through Walls
  code: c62f0e=60
  enable
```

SNES9xEX doesn't write the 'enable' line to the _.cht_ file.  Sega _.pat_ files work as do GBC _.gbcht_ files.  See my WordPress for brief description of [cheats](https://noabody.wordpress.com/2022/06/30/android-emu-cheats/).

This is with UNIX style cheat file with LineFeeds rather than Windows style Carriage Return/LineFeeds or Mac style Carriage Return.  I don't think the format is relevant since SNES9xEX writes to the cheat file which would change the formatting to Android style?

Tested with release 1.5.59 and 1.5.60.

### Steps to reproduce

Use program, select cheat, exit program.

### Expected behavior

'enable' line should be written to _.cht_ file.

**Comment by Rakashazi** [comment]
Thanks for the report. I accidentally left out a function that updates the .cht file when a cheat is toggled but it's fixed in the last commit. If using an older version, a work-around is to set all the cheats you want on/off, then create a dummy cheat and delete it to force the .cht file to update.
