### ISSUE TITLE
[Issue]: fails to launch games

### ISSUE THREAD

**Issue by calebjosephchambers** [Rakashazi/emu-ex-plus-alpha#520]
### Describe the bug

Whenever I try to launch the game through launchBox , the app says permission denied can't access the file.. But when I go through the app and launch games that way, it works Without any problems.

### Steps to reproduce

 Launch games through any  Emulator front-end.

### Expected behavior

When I launch a game through any emulator front end they work, but not Nintendo  Handhelds  And the nintendo and super nintendo.

**Comment by Rakashazi** [comment]
Are you running Android 11+? After that version the only way for the app to access files is via the Storage Access Framework due to an update to the Play Store's policies from last year. Check that your frontend has an option to send paths using this method (they will start with content://com.android.externalstorage.documents/...), and if not, please send a request to the frontend author to add support for it.
