### ISSUE TITLE
[Feature request]: nsf player 

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#634]
### Describe the feature

Hello Mr. Robert, can you add nes NSF Player as a developer to nsf music player
in version 1.5.62 please because I would like to see a music player for emulator 1.5.62, will there be such a function in this version

**Comment by TheBoxGame** [comment]
> ### Opisz funkcję
Witam Panie Robercie czy możecie dodać nes NSF Player jako developer do odtwarzacza muzyki nsf w wersji 1.5.62 prosze bo chciałbym zobaczyc odtwarzacz muzyki do emulatora nes.emu czy bedzie taka funkcja w tej wersji

**Comment by TheBoxGame** [comment]
![Screenshot_2022-08-23-14-24-47-010_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186157428-060be5ee-8392-4c2a-aa9b-68de9d9a86c7.jpg)
![Screenshot_2022-08-23-14-13-28-021_com mi android globalFileexplorer](https://user-images.githubusercontent.com/109180532/186157439-cb0d1b4c-1eb3-451f-8f83-9e5d481319d0.jpg)
![Screenshot_2022-08-23-14-13-13-979_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186157442-de8b4dd4-c9f8-4712-adf4-029e296f2b8a.jpg)

**Comment by soundsnow** [comment]
I don't think it's necessary at all because I've already submitted a lot of issues that will expire if the developer don't deal with them before it's too late
Expired means they will not be noticed and resolved

zx tune is a better choice
Free, ad-free, open source

this is an emulator and playing music resources will consume additional performance

If you add a music player to consider more features, such as progress bars, play history and others

I think Debugger is more necessary to add to the emulator than Chiptunes player

ZXTune
[Google Play](https://play.google.com/store/apps/details?id=app.zxtune)
[Bitbucket](https://bitbucket.org/zxtune/zxtune/src/develop/)
[GitHub](https://github.com/vitamin-caig/zxtune)

Supported formats:
- ZX Spectrum (ASC, FTC, GTR, PSC, PSG, PSM, PT1/PT2/PT3, SQT, STC/ST1/ST3, STP, VTX, YM, TurboSound tracks, AY with embedded player, TXT files for Vortex Tracker II, CHI, DMM, DST, ET1, PDT, SQD, STR, TFC, TFD, TFE)
- PC (669, AMF, AMS, C67, DMF, DSM, FAR, FMT, FNK, GDM, IMF, IT, J2B, LIQ, PLM, PSM, MDL, MO3, MT2, MTM, PTM, RTM, S3M, STIM, STM, STX, ULT, V2M, XM)
- Amiga (DBM, EMOD, MOD, IMS, MED, OKT, SFX, AHX)
- Atari (DTM, GTK, TCB, SAP, RMT)
- Acorn (DTT)
- Sam Coupe (COP)
- Commodore 64/128 MOS6581 (SID)
- Amstrad CPC (AYC)
- Super Nintendo (SPC)
- Multiplatform (MTC, VGM, GYM)
- Nintendo (NSF, NSFe)
- GameBoy (GBS, GSF)
- TurboGrafX (HES)
- MSX (KSS)
- PlayStation (PSF, PSF2, AT3, AT9)
- Ultra64 (USF)
- Nintendo DS (2SF, NCSF)
- Dreamcast (DSF)
- Saturn (SSF)
- Generic (MP3, OGG, WAV, FLAC)
- XSPF (import and export) and AYL (import only) playlists
- Archives (ZIP, RAR, LHA, UMX, GZip, 7zip and FSB)

**Comment by TheBoxGame** [comment]
yes, but this emulator is as fceux and nsfplayer would be really handy even though it will drop on performance

**Comment by TheBoxGame** [comment]
and specially download the player only for the one in the application, it will be better because you have a music player in nes.emu and so you have to download additional applications

**Comment by soundsnow** [comment]
someone mentioned nsf before, but it was closed without replying

**Comment by TheBoxGame** [comment]
I am surprised by one nsf player, it can also be ready, I don't know what the developer meant because I wrote about new mappers and the nsf player and he wrote it, I'm curious what he meant

**Comment by TheBoxGame** [comment]
I wrote to him about it before

**Comment by TheBoxGame** [comment]
these games have a problem

![Screenshot_2022-08-23-14-07-00-734_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186188275-88450a4b-d883-4505-841b-0b219c8f3691.jpg)
![Screenshot_2022-08-23-14-06-20-754_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186188284-34e92649-8a65-4e77-a288-8f454d3d3011.jpg)


INES Mapper 134
INES Mapper 342
INES Mapper 176 
INES Mapper 413

**Comment by TheBoxGame** [comment]
![3](https://user-images.githubusercontent.com/109180532/186195235-5cdd251c-22f8-4a7d-8f1a-ab48c127031d.PNG)
![11合1(MMK-02D-00)(其他版)_11-in-1 (MMK-02D-00) (Unl)](https://user-images.githubusercontent.com/109180532/186195245-f0f94494-f515-43a6-ae42-8cd7c2f3f0ca.png)
![10合1(MMK-02A-01)(其他版)_10-in-1 (MMK-02A-01) (Unl)](https://user-images.githubusercontent.com/109180532/186195249-f81ea5e4-fef1-4533-86c6-312111918af0.png)

**Comment by TheBoxGame** [comment]
Boat Race (Eliminator Boat Duel hack) (VT03) (Unl).nes
![Screenshot_2022-08-23-17-34-48-306_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186201213-ef97fe9e-536b-4685-80ce-caca0734dd29.jpg)

**Comment by Rakashazi** [comment]
Hi, an NSF player is possible but it's low priority since I don't want to add the additional overhead of background processing and music controls to the app. I can add a basic implementation in the future but no ETA. Also, @TheBoxGame please don't post the same issue multiple times. Right now you have 5 different NSF player requests so I'm deleting the others.

**Comment by TheBoxGame** [comment]
OK

**Comment by TheBoxGame** [comment]
it may even be but what does this abbreviation ETA mean

**Comment by TheBoxGame** [comment]
and you can name the players?

**Comment by TheBoxGame** [comment]
and in nes.emu 1.5.63 you can do such an implementation but without ETA

**Comment by Rakashazi** [comment]
@TheBoxGame once again, please don't post multiple new issues about NSF playback, otherwise you'll get a temporary ban from posting.

**Comment by TheBoxGame** [comment]
OK

**Comment by TheBoxGame** [comment]
> @TheBoxGamejeszcze raz, proszę nie publikować wielu nowych problemów dotyczących odtwarzania NSF, w przeciwnym razie dostaniesz tymczasowy zakaz publikowania.

OK

**Comment by TheBoxGame** [comment]
well I understand, just add an implementation of this function because fceux has this function and nes.emu is based on fceux right?

**Comment by TheBoxGame** [comment]
nes.emu attracts me to even 1000 fps in the benchmark
![Screenshot_2022-09-11-02-43-56-265_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/189506734-a63d9b1b-6b4e-41b5-a93b-bc028dd573ee.jpg)

**Comment by TheBoxGame** [comment]
hardly thought that this feature would be in version 1.5.64 because the emulator is really developing

**Comment by TheBoxGame** [comment]
![Screenshot_2022-09-11-02-43-56-265_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/189506887-5c4f0fd5-04b7-432d-8062-373afd5fd6eb.jpg)
