### ISSUE TITLE
[Feature request]: c64 bios

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#739]
### Describe the feature

[Commodore - 8-bit (VICE).zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9603691/Commodore.-.8-bit.VICE.zip)

Commodore - 8-bit (VICE).zip/data
342 files

C64.emu.zip/C64.emu/
329 files

**Comment by Rakashazi** [comment]
C64.emu is tested against the BIOS files from VICE's GTK3 binary distribution:

https://vice-emu.sourceforge.io/index.html#download

You can use other BIOS file sets but it's not guaranteed they'll work, and the amount of files in them is not relevant since they can be for other C64 emulators or different versions of VICE.
