### ISSUE TITLE
[Feature request]: screenshots, cheats, patches, palettes App Folder

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#764]
### Describe the feature

Screenshots: App Folder
Android/data/com.explusalpha.xxxEmu/files/EmuEx/xxx/screenshots

Cheats: App Folder
Android/data/com.explusalpha.xxxEmu/files/EmuEx/xxx/cheats

Patches: App Folder
Android/data/com.explusalpha.xxxEmu/files/EmuEx/xxx/patches

Palettes: App Folder
Android/data/com.explusalpha.xxxEmu/files/EmuEx/xxx/palettes

Saves: App Folder
Android/data/com.explusalpha.xxxEmu/files/EmuEx/xxx/saves

**Comment by Rakashazi** [comment]
I'd rather not store more things in the app's private folder since it was just meant as a fallback if the device had write permission issues. I may move everything there into the app media folder Android/media/com.explusalpha.xxx in a future update since it's accessible to other apps like file managers on the device.

**Comment by TheBoxGamePL** [comment]
Rakashazi I have a question, would you add 5 mappers to nes.emu
INES 134
INES 176
INES 502
INES 295
INES 353

**Comment by TheBoxGamePL** [comment]
did you add them earlier because I need these 5 mappers

**Comment by TheBoxGamePL** [comment]
because i found some roms i had in childhood and i would like to recreate them in nes.emu but they don't work properly
7 in 1 YH708 has a problem running games
the menu works but no games have been started

**Comment by TheBoxGamePL** [comment]
add mappers nes.emu 1.5.65 plis
