### ISSUE TITLE
[Feature request]: Option to revert to older save system 

### ISSUE THREAD

**Issue by juamnitruh** [Rakashazi/emu-ex-plus-alpha#824]
### Describe the feature

I prefer it because i could use saves between emulators.
I just updated to the lastest build, and the new save system just cleaned my .srm's every time i open a game. Why can't i just use a .srm i already have? 

I'm not a fan of auto saving and loading in the first place, but it can be convenient for some, so i think a switch on/off would be the best option.

**Comment by Rakashazi** [comment]
Depending on the system, save states also include the SRAM data so any time you update a save memory file outside the emulator, you should delete the autosave state otherwise the SRAM contents will be replaced when it's loaded.

I understand not everyone wants to launch games with a save state automatically loading, so I added Options -> System -> Autosave Launch Mode -> Load (No State) in the last commit. This will only load the SRAM when you start playing but still give you access to saving/loading the autosave state while you play. Give it a try and let me know any feedback.

**Comment by juamnitruh** [comment]
> Depending on the system, save states also include the SRAM data so any time you update a save memory file outside the emulator, you should delete the autosave state otherwise the SRAM contents will be replaced when it's loaded.
> 
> I understand not everyone wants to launch games with a save state automatically loading, so I added Options -> System -> Autosave Launch Mode -> Load (No State) in the last commit. This will only load the SRAM when you start playing but still give you access to saving/loading the autosave state while you play. Give it a try and let me know any feedback.

I tried that, and seems like everything is fine now. But, when i first installed it, even when i wasn't loading any state at all, my saves where erased anyway. I guess i had to have the option "load (no state)" on, since even with the "ask" option, my saves were being erased.

To be more specific, it's not that my saves were being literally deleted, the .srm was still there, the emulator just had overwritten it with nothing, so it wasn't a issue of loading a state either. 

Well it's fixed for me now, thanks for replying.

**Comment by Rakashazi** [comment]
No problem, it's possible there was a stale save state in the autosave slot that was at game boot so it looked like nothing was getting loaded but it contained empty SRAM so that would have wiped your saves. To be extra safe, I added an alert message in the last commit if the app launches a game and auto loads any state with a file modified time older than the SRAM.
