### ISSUE TITLE
Games cannot save to external storage on Android 5/6, no permissions.

### ISSUE THREAD

**Issue by gannon345** [Rakashazi/emu-ex-plus-alpha#83]
With save location set to "Same as game," the save state fails if the game ROM is located on external storage, and setting switches back to default.

For those who would prefer to keep their games and save files on external, would it be possible for you to add WRITE_EXTERNAL_STORAGE permissions to the .emu series apps and have it prompt for permission on newer versions of Android?

**Comment by xperia64** [comment]
I'm assuming that by "external storage" you mean an SD Card or a USB drive, correct? These emulators already request the WRITE_EXTERNAL_STORAGE permission which only allows the app to write to the internal storage partition aka "/storage/emulated/0". It is currently difficult to write things to true external storage due to the way android handles writing things there (they won't even let you move files to other folders last time I checked).

Another side note, this project does request the WRITE_MEDIA_STORAGE permission, which if you are rooted and have a certain Xposed module installed, might let these apps write to external storage.

**Comment by gannon345** [comment]
"It is currently difficult to write things to true external storage due to
the way android handles writing things there (they won't even let you move
files to other folders last time I checked)."

That's what I'm referring to. Android 5 and 6 implemented new permissions
that allow apps to request request permissions to write to external
(microSD/USB drives). It's been a standard option for a while now, and many
apps and some emulators use it now.

**Comment by Rakashazi** [comment]
Closing out some old issues, should be addressed in storage updates since last post.
